# Generated by Django 4.2.11 on 2024-04-21 10:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moviename', models.CharField(default='', max_length=100, null=True)),
                ('descriptions', models.CharField(default='', max_length=200)),
                ('categories', models.CharField(default='', max_length=50)),
                ('actors_name', models.TextField(default='')),
                ('youtube_link', models.URLField(default='')),
                ('images', models.ImageField(upload_to='post_images')),
                ('rdate', models.DateField()),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
