# Generated by Django 4.2.11 on 2024-04-27 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mthapp', '0009_profile_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fav',
        ),
        migrations.AddField(
            model_name='post',
            name='fav',
            field=models.ManyToManyField(blank=True, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
