# Generated by Django 4.2.11 on 2024-04-28 07:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mthapp', '0010_remove_profile_fav_post_fav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fav',
        ),
        migrations.AddField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favourites',
        ),
    ]
