# Generated by Django 4.2.11 on 2024-04-30 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mthapp', '0011_remove_post_fav_post_favourites_delete_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mthapp.genre'),
            preserve_default=False,
        ),
    ]
