# Generated by Django 4.2.11 on 2024-04-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mthapp', '0013_alter_post_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
