# Generated by Django 4.2.11 on 2024-04-30 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mthapp', '0014_remove_post_genre_delete_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='typegenre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mthapp.genretype'),
        ),
    ]
