# Generated by Django 4.2.11 on 2024-04-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mthapp', '0015_genretype_post_typegenre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='typegenre',
            new_name='genretype',
        ),
    ]
