# Generated by Django 4.2.11 on 2024-05-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mthapp', '0018_category_remove_post_categories_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/blankprofile.png', upload_to='profile_pictures'),
        ),
    ]
